In [2]:
#importing numpy
import numpy as np

In [57]:
#creating a array
array_1=np.array([4,4,2])

In [58]:
array_1

array([4, 4, 2])

In [8]:
#basic function for array
#shape and size of a matrix
array_1.shape

(3,)

In [6]:
array_1.size

3

In [68]:
#which type of array is
array_1.dtype


dtype('int32')

In [69]:
#to get dimension of any array
array_1.ndim

1

In [9]:
#arange--add element in a array from given start to end-1
array_2=np.arange(0,10)

In [10]:
array_2


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Random

Function

In [12]:
#thorugh this we can take a random integer from a given range and make a array of any size containing element from that range



In [13]:
#by executing below statement we will get an array of size 4x4 containing element in range 0 to 4
array_3=np.random.randint(0,4,size=(4,4))

In [14]:
array_3

array([[3, 0, 2, 1],
       [1, 1, 2, 3],
       [0, 3, 3, 3],
       [0, 2, 3, 2]])

In [17]:
#np.random.rand both are used for having floating element as values in array

array_4=np.random.rand(5,3)

In [18]:
array_4

array([[0.22654021, 0.00895153, 0.4867367 ],
       [0.75054598, 0.34379504, 0.79162603],
       [0.42157267, 0.25014471, 0.64576995],
       [0.68921435, 0.48970221, 0.13841239],
       [0.26061696, 0.44467779, 0.85844518]])

In [25]:
#if in the () is not given it will generate a random float integer if any integer in mentioned then an array is returned with size equals integer  
num_1=np.random.random()

In [26]:
num_1

0.06889325761140919

In [32]:
#below statement will generate a number from given range if box contain only one element then starting is considered as o and size zero
num_2=np.random.randint(6)

In [33]:
num_2

1

In [35]:
#everytime we execute command containing random function it will generate a new number if we wish to hold the number generated in first time we have to use function
#np.random.seed()
#you can put seed= anything in braces

In [53]:
np.random.seed(seed=2)
num_3=np.random.randint(5)
num_3

0

View a array/matrix

In [54]:
#we have two array (array_3,array_2)

In [60]:
#to see element without repetiton of any  array in sorted sequence we use 
np.unique(array_3)

array([0, 1, 2, 3])

In [61]:
array_3

array([[3, 0, 2, 1],
       [1, 1, 2, 3],
       [0, 3, 3, 3],
       [0, 2, 3, 2]])

In [67]:
#to see slected numbers of rows and element
#we use
array_3[:2,:2]

array([[3, 0],
       [1, 1]])

In [65]:
np.unique(temp)

array([ 0,  1,  2,  3, 10])

## manipulating and comapring

airthmetic operation

In [70]:
#usually these operations are applied on matrix of same size
arr_1=np.random.randint(1,9,size=(3,3))
arr_2=np.random.randint(2,11,size=(3,3))


In [71]:
#each element is divided by coresponding element from another matrices
arr_2/arr_1

array([[0.5       , 0.5       , 7.        ],
       [0.85714286, 1.5       , 2.33333333],
       [2.25      , 5.        , 1.        ]])

In [72]:
##each element is multiplied by coresponding element from another matrices
arr_2*arr_1


array([[32, 18,  7],
       [42, 24, 21],
       [36,  5, 64]])

In [73]:
#each element is added by coresponding element from another matrices
arr_2+arr_1

array([[12,  9,  8],
       [13, 10, 10],
       [13,  6, 16]])

In [74]:
#floor division and modolous
arr_2//arr_1

array([[0, 0, 7],
       [0, 1, 2],
       [2, 5, 1]])

In [75]:
#it will return element raise to power equals to given integer
arr_2**2

array([[16,  9, 49],
       [36, 36, 49],
       [81, 25, 64]])

In [76]:
#exponential and lograthimic
np.exp(arr_1)

array([[2.98095799e+03, 4.03428793e+02, 2.71828183e+00],
       [1.09663316e+03, 5.45981500e+01, 2.00855369e+01],
       [5.45981500e+01, 2.71828183e+00, 2.98095799e+03]])

In [77]:
np.log(arr_2)

array([[1.38629436, 1.09861229, 1.94591015],
       [1.79175947, 1.79175947, 1.94591015],
       [2.19722458, 1.60943791, 2.07944154]])

In [78]:
#to find sum of element of array we use
np.sum(arr_2)

55

In [79]:
#we have a another sum function in basic python but sum from numpy module is very fast
#we can check it by using '%time it ' function 

In [80]:
#reshaping a matrix
arr_3=np.array([[1,3,1],[3,4,1]])

In [81]:
arr_3

array([[1, 3, 1],
       [3, 4, 1]])

In [82]:
arr_3.reshape(2,3,1)

array([[[1],
        [3],
        [1]],

       [[3],
        [4],
        [1]]])

Dot product

In [85]:
#there is difference in multiplication and dot product of a array
#for dot product no. of coloumn of first and no. of row must be same

In [86]:
arr_1.dot(arr_2)

array([[ 77,  65, 106],
       [ 79,  60, 101],
       [ 94,  58,  99]])

Transposing a matrix

In [87]:
#simple use this line
arr_1.T

array([[8, 7, 4],
       [6, 4, 1],
       [1, 3, 8]])

In [88]:
arr_1

array([[8, 6, 1],
       [7, 4, 3],
       [4, 1, 8]])

Sorting 

In [91]:
#sort rows 
np.sort(arr_1)

array([[1, 6, 8],
       [3, 4, 7],
       [1, 4, 8]])

In [92]:
#return index of element according to desired location after solving
np.argsort(arr_1)

array([[2, 1, 0],
       [2, 1, 0],
       [1, 0, 2]], dtype=int64)

In [101]:
# min function will return min value from row if (axis =1) and from coloumn if (axis =0)
np.min(arr_1,axis=0)

array([4, 1, 1])

## Importing Image in Array 

In [102]:
#we use imread function from matplotlib

In [111]:
from matplotlib.image import imread



In [109]:
##you can transer any image in array and numbers shown in array will be pixels


In [106]:
img=imread("lol_1.jpg")

In [107]:
img

array([[[210, 176, 139],
        [214, 180, 142],
        [217, 183, 145],
        ...,
        [189, 160, 128],
        [189, 160, 128],
        [190, 161, 129]],

       [[204, 170, 133],
        [210, 176, 138],
        [217, 183, 145],
        ...,
        [184, 155, 123],
        [184, 155, 123],
        [183, 154, 122]],

       [[196, 162, 125],
        [205, 171, 134],
        [216, 182, 144],
        ...,
        [186, 157, 125],
        [185, 156, 124],
        [183, 154, 122]],

       ...,

       [[ 16,  10,  14],
        [ 16,  10,  14],
        [ 17,  11,  15],
        ...,
        [123, 105,  83],
        [122, 104,  82],
        [123, 105,  83]],

       [[ 16,  10,  14],
        [ 16,  10,  14],
        [ 17,  11,  15],
        ...,
        [121, 103,  81],
        [119, 101,  79],
        [120, 102,  80]],

       [[ 16,  10,  14],
        [ 17,  11,  15],
        [ 18,  12,  16],
        ...,
        [121, 103,  81],
        [116,  98,  76],
        [115,  97,  75]]

Till now i showed you how to use basic function of numpy module in python,
commands by ayush pareek